apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rpxuh4urd-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:82c2e60f33406be7aef2f8fcbf549790da0d8393@sha256:c479665fc6a736ff1075f05613d08aaee6cee5c63b35d2a2e5137d4f424aa24e
          name: container-image
